---
title: "Speedcubing Dominance"
format: 
  html:
     df-print: paged
     embed-resources: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
```

## Appearances in Top 100 Solves Per Year

```{r solves}
top_singles = read_excel("Top100CubersPerYear.xlsx", sheet = "Top100Singles")

top_per_year = top_singles %>% group_by(Year, Name) %>%
 summarise(Appearances = n(), .groups = "drop") %>% arrange(desc(Appearances))

top_per_year
```

## Most Appearances in Top 100 Solves Per Year

```{r most dominant singles}
dominant = top_per_year %>% group_by(Year) %>%
  filter(Appearances == max(Appearances)) %>% arrange(Year)

dominant
```

## Appearances in Top 100 Averages Per Year

```{r averages}
top_averages = read_excel("Top100CubersPerYear.xlsx", sheet = "Top100Averages")

top_per_year_avg = top_averages %>% group_by(Year, Name) %>%
  summarise(Appearances = n(), .groups = "drop") %>% arrange(desc(Appearances))

top_per_year_avg
```

## Most Appearances in Top 100 Averages Per Year

```{r most dominant averages}
dominant_avg = top_per_year_avg %>% group_by(Year) %>%
  filter(Appearances == max(Appearances)) %>% arrange(Year)

dominant_avg

```

## Total Appearances in Both Top 100s

```{r appearances both}
dominant_both = top_per_year_avg %>%
  left_join(top_per_year, by = c("Year", "Name")) %>%
  mutate(Appearances.x = replace_na(Appearances.x, 0),
         Appearances.y = replace_na(Appearances.y, 0)) %>%
  mutate(Total_Appearances = Appearances.x + Appearances.y) %>%
  arrange(desc(Total_Appearances), desc(Appearances.x)) %>% 
  select(Year, Name, Total_Appearances)

dominant_both
```

## Most Dominant Cubers Per Year

```{r most dominant}
most_dominant = dominant_both %>% group_by(Year) %>%
  filter(Total_Appearances == max(Total_Appearances)) %>% arrange(Year)

most_dominant
```
